import { SupplyItem } from './types';

export const SUPPLY_DATA: SupplyItem[] = [
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Оцинкованная стальная полоса 40х4мм",
    "unit": "тонна",
    "qty": 4.51,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/18",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев, Жасулан Туякбаев ПГУ",
    "title": "Алпыспаев Азамат"
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Шина заземления (луженая медная шина 1000х10х60мм)",
    "unit": "кг",
    "qty": 350,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/19",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Провод в ПВХ изоляции ПВ-3, сечение 1х400",
    "unit": "м",
    "qty": 644,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/20",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Провод в ПВХ изоляции ПВ-3, сечение 1х120",
    "unit": "м",
    "qty": 75,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/21",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Провод в ПВХ изоляции ПВ-3, сечение 1х95",
    "unit": "м",
    "qty": 193,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/22",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Провод в ПВХ изоляции ПВ-3, сечение 1х70",
    "unit": "м",
    "qty": 115,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/23",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Провод в ПВХ изоляции ПВ-3, сечение 1х35",
    "unit": "м",
    "qty": 1477,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/24",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Провод в ПВХ изоляции ПВ-3, сечение 1х25",
    "unit": "м",
    "qty": 92,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/25",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Провод в ПВХ изоляции ПВ-3, сечение 1х16",
    "unit": "м",
    "qty": 298,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/26",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Провод в ПВХ изоляции ПВ-3, сечение 1х10",
    "unit": "м",
    "qty": 568,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/27",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Наконечник медный для кабеля, сечением 400",
    "unit": "шт",
    "qty": 172,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/28",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Наконечник медный для кабеля, сечением 120",
    "unit": "шт",
    "qty": 24,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/29",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Наконечник медный для кабеля, сечением 95",
    "unit": "шт",
    "qty": 124,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/30",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Наконечник медный для кабеля, сечением 70",
    "unit": "шт",
    "qty": 32,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/31",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Наконечник медный для кабеля, сечением 35",
    "unit": "шт",
    "qty": 658,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/32",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Наконечник медный для кабеля, сечением 25",
    "unit": "шт",
    "qty": 22,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/33",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Наконечник медный для кабеля, сечением 16",
    "unit": "м",
    "qty": 399,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/34",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Наконечник медный для кабеля, сечением 10",
    "unit": "шт",
    "qty": 198,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/35",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Скоба-держатель полосы 40х4",
    "unit": "шт",
    "qty": 3780,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/36",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Универсальный зажим для круглых проводников",
    "unit": "шт",
    "qty": 251,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/37",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Заземляющая клемма для круглых и плоских проводников",
    "unit": "шт",
    "qty": 201,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/38",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Набор для термосварки 40*4 и кабеля 400мм2",
    "unit": "шт",
    "qty": 63,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/39",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Набор для термосварки 40*4 и кабеля 120мм2",
    "unit": "шт",
    "qty": 16,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/40",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Набор для термосварки 40*4 и кабеля 95мм2",
    "unit": "шт",
    "qty": 8,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/41",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Набор для термосварки 40*4 и кабеля 70мм3",
    "unit": "шт",
    "qty": 16,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/42",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Набор для термосварки 40*4 и кабеля 35мм2",
    "unit": "шт",
    "qty": 347,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/43",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Набор для термосварки 40*4 и кабеля 16мм2",
    "unit": "шт",
    "qty": 24,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/44",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Набор для термосварки 40*4 и кабеля 10мм2",
    "unit": "шт",
    "qty": 84,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/45",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Уплотнительная втулка для плоских проводников",
    "unit": "шт",
    "qty": 17,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/46",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Крестовой соединитель DIN для плоских проводников",
    "unit": "шт",
    "qty": 97,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/47",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Муфта стальная D25мм",
    "unit": "шт",
    "qty": 299,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/48",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Направляющий U профиль (одинарный, для фиксации трубного хомута диаметром 25мм)",
    "unit": "шт",
    "qty": 304,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/49",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Держатель прута на трубе D=(48-53) мм HZ EKF PROxima",
    "unit": "шт",
    "qty": 304,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/50",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "ПВХ труба диаметром 50мм",
    "unit": "м",
    "qty": 316,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/51",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "ПВХ труба диаметром 32мм",
    "unit": "м",
    "qty": 161,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/52",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "ПВХ труба диаметром 25мм",
    "unit": "м",
    "qty": 1799,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/53",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Труба стальная оцинкованная, диаметром 25мм",
    "unit": "м",
    "qty": 599,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/54",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Труба стальная оцинкованная, диаметром 57мм",
    "unit": "м",
    "qty": 575,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/55",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №1",
    "date": "20.08.2025",
    "material": "Держатель оценкованный двусторонний д.63мм",
    "unit": "шт",
    "qty": 1150,
    "note": "Заземление",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка обновлена от 03.09.2025 смотрите ниже заявки под №17/56",
    "deliveryDate": "-",
    "daysInWork": "194",
    "responsible": "Нурсултан Орынтаев",
    "title": ""
  },
  {
    "id": "Заявка №2",
    "date": "02.09.2025",
    "material": "Мастика УМС-50",
    "unit": "м",
    "qty": 28.08,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №2",
    "date": "02.09.2025",
    "material": "Шнур гернит 30",
    "unit": "м",
    "qty": 28.08,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"ЭКОШИН\"",
    "deliveryDate": "",
    "daysInWork": "10.09.2025",
    "responsible": "8",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №2",
    "date": "02.09.2025",
    "material": "Пена монтажная",
    "unit": "л",
    "qty": 104,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "06.09.2025",
    "responsible": "4",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №2",
    "date": "02.09.2025",
    "material": "Цемент М200",
    "unit": "кг",
    "qty": 25,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "06.09.2025",
    "responsible": "4",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №2",
    "date": "02.09.2025",
    "material": "Песок речной",
    "unit": "кг",
    "qty": 44,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "10.09.2025",
    "responsible": "8",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Канализация химически загрязненных стоков К34Н",
    "unit": "",
    "qty": "",
    "note": "COMPLETE",
    "status": "6. Заявка отменена",
    "supplier": "Заявка не актуальна",
    "comment": "",
    "deliveryDate": "-",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Труба сталь диам 108*4 прямошовная",
    "unit": "м",
    "qty": 60,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Труба сталь диам 89*3,5 прямошовная",
    "unit": "м",
    "qty": 150,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Клапан обратный Ру10, Ду80",
    "unit": "шт",
    "qty": 12,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Задвижка с обрезиненным клином, фланцевая Ру10 DN80",
    "unit": "шт",
    "qty": 8,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Гибкая вставка фланцевая Ру16 Ду80",
    "unit": "шт",
    "qty": 8,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Переход стальной приварной Д180*4-89*3,5",
    "unit": "шт",
    "qty": 2,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Тройник стальной бесшовный приварной Ру10, диам 108*89",
    "unit": "шт",
    "qty": 4,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Тройник стальной бесшовный приварной Ру10, диам 89*3,5",
    "unit": "шт",
    "qty": 4,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Отвод стальной приварной 90гр, Ру10, 108*5",
    "unit": "шт",
    "qty": 7,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Отвод стальной приварной 90гр, Ру10, 89*3,5",
    "unit": "шт",
    "qty": 24,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Фланец стальной приварной плоский с соединительным выступом Ду80 3сп Ру16",
    "unit": "шт",
    "qty": 56,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Окраска труб и креплений трубопровода масляной краской",
    "unit": "м2",
    "qty": 60,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №3",
    "date": "02.09.2025",
    "material": "Крепление для трубопровода/кронштейны, планки, хомуты",
    "unit": "кг",
    "qty": 170,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявка не актуальна",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Канализация аварийных маслостоков К16",
    "unit": "",
    "qty": "ЦА",
    "note": "COMPLETE",
    "status": "6. Заявка отменена",
    "supplier": "Заявку обновили, внесли корректировки",
    "comment": "",
    "deliveryDate": "-",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Труба чугунная напорная с раструбным соединением Акл, ДН200",
    "unit": "м",
    "qty": 330,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Труба чугунная напорная с раструбным соединением Акл, ДН100",
    "unit": "м",
    "qty": 8,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Тройник раструбный Ду 200*200",
    "unit": "шт",
    "qty": 44,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Тройник раструбный Ду 200*100",
    "unit": "шт",
    "qty": 4,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Колена раструб гладкий конец 90гр Ду200",
    "unit": "шт",
    "qty": 26,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Колена раструб гладкий конец 90гр Ду100",
    "unit": "шт",
    "qty": 4,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Крестовина раструбная Ду200",
    "unit": "шт",
    "qty": 1,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Трап чугунный с вертикальным отводом Ду100",
    "unit": "шт",
    "qty": 4,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Патрубок фланец - раструб L=1200 Ду200",
    "unit": "шт",
    "qty": 29,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Заглушка фланцевая Ду 200",
    "unit": "шт",
    "qty": 29,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Двойной раструб Ду200",
    "unit": "шт",
    "qty": 58,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Канализация дизельного топлива К18",
    "unit": "",
    "qty": "ЦА",
    "note": "COMPLETE",
    "status": "6. Заявка отменена",
    "supplier": "Заявку обновили, внесли корректировки",
    "comment": "",
    "deliveryDate": "-",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Труба чугунная напорная с раструбным соединением Акл, ДН200",
    "unit": "м",
    "qty": 245,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Тройник раструбный Ду 200*200",
    "unit": "шт",
    "qty": 16,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Колена раструб гладкий конец 90гр Ду200",
    "unit": "шт",
    "qty": 13,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Крестовина раструбная Ду200",
    "unit": "шт",
    "qty": 1,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Патрубок фланец - раструб L=1200 Ду200",
    "unit": "шт",
    "qty": 16,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Заглушка фланцевая Ду 200",
    "unit": "шт",
    "qty": 16,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Двойной раструб Ду200",
    "unit": "шт",
    "qty": 40,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Заявку обновили, внесли корректировки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Ербол Асенов",
    "title": ""
  },
  {
    "id": "Заявка №5",
    "date": "02.09.2025",
    "material": "Канализация производственная (маслосодержащая) К3",
    "unit": "",
    "qty": "",
    "note": "COMPLETE",
    "status": "6. Заявка отменена",
    "supplier": "",
    "comment": "",
    "deliveryDate": "-",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №5",
    "date": "02.09.2025",
    "material": "Схемы систем К7Н",
    "unit": "",
    "qty": "",
    "note": "COMPLETE",
    "status": "6. Заявка отменена",
    "supplier": "",
    "comment": "",
    "deliveryDate": "-",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №54",
    "date": "02.09.2025",
    "material": "Шайба сталь 120*120*30",
    "unit": "шт",
    "qty": 1,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ИП Айсултан",
    "deliveryDate": "",
    "daysInWork": "30.09.2025",
    "responsible": "28",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №54",
    "date": "02.09.2025",
    "material": "Шайба сталь 424*230*20",
    "unit": "шт",
    "qty": 5,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ИП Айсултан",
    "deliveryDate": "",
    "daysInWork": "30.09.2025",
    "responsible": "28",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №54",
    "date": "02.09.2025",
    "material": "Анкер болт М36 L=1300мм + гайка 2шт",
    "unit": "комплект",
    "qty": 1,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ИП Айсултан",
    "deliveryDate": "",
    "daysInWork": "30.09.2025",
    "responsible": "28",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №54",
    "date": "02.09.2025",
    "material": "Шайба сталь 100*100*35",
    "unit": "шт",
    "qty": 24,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ИП Айсултан",
    "deliveryDate": "",
    "daysInWork": "30.09.2025",
    "responsible": "28",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №54",
    "date": "02.09.2025",
    "material": "Анкер болт М36 L=1020мм + гайка 2шт",
    "unit": "комплект",
    "qty": 16,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ИП Айсултан",
    "deliveryDate": "",
    "daysInWork": "30.09.2025",
    "responsible": "28",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №48",
    "date": "02.09.2025",
    "material": "Шпилька SD1-13*150-A в комплекте с керамическим кольцом",
    "unit": "комплект",
    "qty": 6350,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №48",
    "date": "02.09.2025",
    "material": "Шпилька SD1-13*100-A",
    "unit": "комплект",
    "qty": 2120,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №37",
    "date": "02.09.2025",
    "material": "Арматура диам 10мм",
    "unit": "тонна",
    "qty": 13.43,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №37",
    "date": "02.09.2025",
    "material": "Уголок 50*5",
    "unit": "тонна",
    "qty": 1.856,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №37",
    "date": "02.09.2025",
    "material": "Уголок 50*6",
    "unit": "тонна",
    "qty": 0.089,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №37",
    "date": "02.09.2025",
    "material": "Полоса 40*4",
    "unit": "тонна",
    "qty": 1.389,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №37",
    "date": "02.09.2025",
    "material": "Арматура диам 16мм",
    "unit": "тонна",
    "qty": 0.0576,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №37",
    "date": "02.09.2025",
    "material": "Арматура диам 12мм",
    "unit": "тонна",
    "qty": 2.958,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №37",
    "date": "02.09.2025",
    "material": "Арматура А240 диам 8мм",
    "unit": "тонна",
    "qty": 1.426,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №37",
    "date": "02.09.2025",
    "material": "Арматура А500 диам 8мм",
    "unit": "тонна",
    "qty": 0.0558,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №37",
    "date": "02.09.2025",
    "material": "Профлист Н57-750-0,8",
    "unit": "м2",
    "qty": 856.5,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №37",
    "date": "02.09.2025",
    "material": "Швеллер 10П",
    "unit": "тонна",
    "qty": 0.1886,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №37",
    "date": "02.09.2025",
    "material": "Уголок 70*5",
    "unit": "кг",
    "qty": 132.02,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Арматура диам 16мм А240",
    "unit": "тонна",
    "qty": 0.06718,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Арматура А500 диам 8мм",
    "unit": "тонна",
    "qty": 0.17418,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Арматура А500 диам 10мм",
    "unit": "тонна",
    "qty": 0.06204,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Арматура А500 диам 12мм",
    "unit": "тонна",
    "qty": 1.2905,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Арматура диам 12мм А240",
    "unit": "тонна",
    "qty": 0.05175,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Арматура А500 диам 14мм",
    "unit": "тонна",
    "qty": 0.71904,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Болт М24*900",
    "unit": "шт",
    "qty": 20,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Болт М16*600",
    "unit": "шт",
    "qty": 84,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Болт М48*600",
    "unit": "шт",
    "qty": 16,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"Bugel\"",
    "deliveryDate": "Материал со склада Базиса 8 шт, остальные отработали с Поставщиком",
    "daysInWork": "17.09.2025",
    "responsible": "15",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Профиль сталь гнутый 120*5 с245",
    "unit": "м.п.",
    "qty": 18.88,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Удалены позиции с заявки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Швеллер 12П",
    "unit": "м",
    "qty": 3.08,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Удалены позиции с заявки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Лист стальной 8мм С245",
    "unit": "м2",
    "qty": 1.32,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Удалены позиции с заявки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Лист стальной 10мм С245",
    "unit": "м2",
    "qty": 3.08,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Удалены позиции с заявки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №43",
    "date": "02.09.2025",
    "material": "Круг диам 12мм",
    "unit": "кг",
    "qty": 4.4,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Удалены позиции с заявки",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Панели цокольные ПЦ1-ПЦ-6",
    "unit": "шт",
    "qty": 22,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Арматура А500 диам 12мм",
    "unit": "тонна",
    "qty": 23.138,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Арматура А240 диам 8мм",
    "unit": "тонна",
    "qty": 0.198,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Арматура А500 диам 8мм",
    "unit": "тонна",
    "qty": 6.902,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Швеллер 10П",
    "unit": "тонна",
    "qty": 2.1328,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Арматура А400 диам 8мм",
    "unit": "тонна",
    "qty": 0.1352,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Труба сталь 108*4",
    "unit": "м",
    "qty": 154,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Сальник Ду100 L=300",
    "unit": "шт",
    "qty": 1,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ИП \"ZM MetalLux\"",
    "deliveryDate": "Изготовление, поставка с города Караганда",
    "daysInWork": "12.09.2025",
    "responsible": "10",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Сальник Ду100 L=200",
    "unit": "шт",
    "qty": 1,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ИП \"ZM MetalLux\"",
    "deliveryDate": "Изготовление, поставка с города Караганда",
    "daysInWork": "12.09.2025",
    "responsible": "10",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Уголок 50*5",
    "unit": "тонна",
    "qty": 0.07806,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Профлист Н57-750-0,8",
    "unit": "м2",
    "qty": 840,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал со склада Базиса",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Сетка 4ср диам 5Вр-1-100",
    "unit": "м2",
    "qty": 118,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"МЛ Канстракшн\"",
    "deliveryDate": "",
    "daysInWork": "19.08.2025",
    "responsible": "-14",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Грунтовка Хс-059",
    "unit": "кг",
    "qty": 10,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"СпецХимСнаб ЮС\"",
    "deliveryDate": "",
    "daysInWork": "30.08.2025",
    "responsible": "-3",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Эмаль Хс-759 серая",
    "unit": "кг",
    "qty": 20,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"СпецХимСнаб ЮС\"",
    "deliveryDate": "",
    "daysInWork": "30.08.2025",
    "responsible": "-3",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Пленка п/э 0,6мм",
    "unit": "м2",
    "qty": 28,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "23.08.2025",
    "responsible": "-10",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №41",
    "date": "02.09.2025",
    "material": "Заклепка 4,8*8",
    "unit": "шт",
    "qty": 3000,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "Материал у Базиса на складе",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №32",
    "date": "02.09.2025",
    "material": "Опоры с седлом Н=1230",
    "unit": "шт",
    "qty": 2,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №32",
    "date": "02.09.2025",
    "material": "Опоры с седлом Н=900",
    "unit": "шт",
    "qty": 2,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №32",
    "date": "02.09.2025",
    "material": "Опоры с седлом Н=1060",
    "unit": "шт",
    "qty": 2,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №32",
    "date": "02.09.2025",
    "material": "Опоры с седлом Н=730",
    "unit": "шт",
    "qty": 2,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №32",
    "date": "02.09.2025",
    "material": "Седло для опоры",
    "unit": "шт",
    "qty": 4,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Насос ручной Ultima P80",
    "unit": "шт",
    "qty": 6,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Манометр GA45GC 700бар",
    "unit": "шт",
    "qty": 6,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Шланг гидравлический НС-7210",
    "unit": "шт",
    "qty": 6,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Гидроцилиндр Enerpac LPL1602 г/п 162тн",
    "unit": "шт",
    "qty": 4,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №4",
    "date": "02.09.2025",
    "material": "Гидроцилиндр Enerpac PSM300 г/п 30тн",
    "unit": "шт",
    "qty": 4,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "06.10.-\"Дирекция по строительству ПГУ\" отработала КП, идут переговоры с компанией HILTI руководством по шпилькам с оборудованием. Данная постака идёт полностью под ключ поставщиком",
    "deliveryDate": "",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №14",
    "date": "02.09.2025",
    "material": "ВК Электрощитовая блока Н1",
    "unit": "",
    "qty": "",
    "note": "COMPLETE",
    "status": "6. Заявка отменена",
    "supplier": "",
    "comment": "",
    "deliveryDate": "-",
    "daysInWork": "181",
    "responsible": "Жасулан Туякбаев ПГУ",
    "title": ""
  },
  {
    "id": "Заявка №57",
    "date": "03.09.2025",
    "material": "Труба квадратная 100*100*3",
    "unit": "м",
    "qty": 396,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ИП \"БАРДЗИМИ\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №57",
    "date": "03.09.2025",
    "material": "Труба квадратная 80*80*3",
    "unit": "м",
    "qty": 180,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ИП \"БАРДЗИМИ\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №57",
    "date": "03.09.2025",
    "material": "Саморез по металлу 5мм",
    "unit": "шт",
    "qty": 3000,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №57",
    "date": "03.09.2025",
    "material": "Шуруповерт",
    "unit": "шт",
    "qty": 2,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №57",
    "date": "03.09.2025",
    "material": "Бита под шуруповерт",
    "unit": "шт",
    "qty": 6,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №57",
    "date": "03.09.2025",
    "material": "Электроды д3мм",
    "unit": "кг",
    "qty": 40,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №57",
    "date": "03.09.2025",
    "material": "Солидол",
    "unit": "кг",
    "qty": 40,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №57",
    "date": "03.09.2025",
    "material": "Маска сварочная",
    "unit": "шт",
    "qty": 4,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №57",
    "date": "03.09.2025",
    "material": "Щиток монитажный прозрачный",
    "unit": "шт",
    "qty": 4,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №57",
    "date": "03.09.2025",
    "material": "Диск диам 180мм",
    "unit": "шт",
    "qty": 40,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №16",
    "date": "03.09.2025",
    "material": "Арматура диам 20мм А240",
    "unit": "тонна",
    "qty": 0.15,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ИП \"БАРДЗИМИ\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №16",
    "date": "03.09.2025",
    "material": "Отвод стальной 108мм",
    "unit": "шт",
    "qty": 4,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "ТОО \"STROY CITY №1\"",
    "deliveryDate": "",
    "daysInWork": "03.09.2025",
    "responsible": "0",
    "title": "Жасулан Туякбаев ПГУ"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Медная полка 80*5мм",
    "unit": "м",
    "qty": 3868,
    "note": "ца",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "21.10.- поставка по графику(Слава менеджер - 87768260202)",
    "daysInWork": "21.10.2025",
    "responsible": "48",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Шина заземления (луженая медная шина 1000х10х60мм)",
    "unit": "шт",
    "qty": 66,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "обьект подал заявку 13.11.2025",
    "daysInWork": "14.12.2025",
    "responsible": "102",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Провод ПВХ ПВ-3 сечением 1*400",
    "unit": "м",
    "qty": 644,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "Поставка завершена ПВ3, но обьект просили заменить ПВ3 на ПВ2. новая заяка поступила на ПВ2 от 08.10.2025",
    "daysInWork": "35 дней",
    "responsible": "#ЗНАЧ!",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Провод ПВХ ПВ-3 сечением 1*120",
    "unit": "м",
    "qty": 75,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "Поставка завершена ПВ3, но обьект просили заменить ПВ3 на ПВ2. новая заяка поступила на ПВ2 от 08.10.2025",
    "daysInWork": "10 дней",
    "responsible": "#ЗНАЧ!",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Провод ПВХ ПВ-3 сечением 1*95",
    "unit": "м",
    "qty": 193,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "Поставка завершена ПВ3, но обьект просили заменить ПВ3 на ПВ2. новая заяка поступила на ПВ2 от 08.10.2025",
    "daysInWork": "10 дней",
    "responsible": "#ЗНАЧ!",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Провод ПВХ ПВ-3 сечением 1*70",
    "unit": "м",
    "qty": 115,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "Поставка завершена ПВ3, но обьект просили заменить ПВ3 на ПВ2. новая заяка поступила на ПВ2 от 08.10.2025",
    "daysInWork": "10 дней",
    "responsible": "#ЗНАЧ!",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Провод ПВХ ПВ-3 сечением 1*35",
    "unit": "м",
    "qty": 2225,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "Поставка завершена ПВ3, но обьект просили заменить ПВ3 на ПВ2. новая заяка поступила на ПВ2 от 08.10.2025",
    "daysInWork": "10 дней",
    "responsible": "#ЗНАЧ!",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Провод ПВХ ПВ-3 сечением 1*25",
    "unit": "м",
    "qty": 92,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "Поставка завершена ПВ3, но обьект просили заменить ПВ3 на ПВ2. новая заяка поступила на ПВ2 от 08.10.2025",
    "daysInWork": "10 дней",
    "responsible": "#ЗНАЧ!",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Провод ПВХ ПВ-3 сечением 1*16",
    "unit": "м",
    "qty": 438,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "Поставка завершена ПВ3, но обьект просили заменить ПВ3 на ПВ2. новая заяка поступила на ПВ2 от 08.10.2025",
    "daysInWork": "10 дней",
    "responsible": "#ЗНАЧ!",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Провод ПВХ ПВ-3 сечением 1*10",
    "unit": "м",
    "qty": 568,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "Поставка завершена ПВ3, но обьект просили заменить ПВ3 на ПВ2. новая заяка поступила на ПВ2 от 08.10.2025",
    "daysInWork": "10 дней",
    "responsible": "#ЗНАЧ!",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Наконечник медный сечение 1*400",
    "unit": "шт",
    "qty": 172,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "на обьекте",
    "daysInWork": "14.11.2025",
    "responsible": "72",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Наконечник медный сечение 1*120",
    "unit": "шт",
    "qty": 24,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "на обьекте",
    "daysInWork": "",
    "responsible": "180",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Наконечник медный сечение 1*95",
    "unit": "шт",
    "qty": 124,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "на обьекте",
    "daysInWork": "",
    "responsible": "180",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Наконечник медный сечение 1*70",
    "unit": "шт",
    "qty": 32,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "на обьекте",
    "daysInWork": "",
    "responsible": "180",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Наконечник медный сечение 1*35",
    "unit": "шт",
    "qty": 940,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "на обьекте",
    "daysInWork": "",
    "responsible": "180",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Наконечник медный сечение 1*25",
    "unit": "шт",
    "qty": 22,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "на обьекте",
    "daysInWork": "",
    "responsible": "180",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Наконечник медный сечение 1*16",
    "unit": "шт",
    "qty": 469,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "на обьекте",
    "daysInWork": "",
    "responsible": "180",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Наконечник медный сечение 1*10",
    "unit": "шт",
    "qty": 198,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "на обьекте",
    "daysInWork": "",
    "responsible": "180",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Скоба-держатель полосы с болтом",
    "unit": "шт",
    "qty": 3868,
    "note": "ЦА",
    "status": "Нурсултан Орынтаев",
    "supplier": "4. Поставка контрагента",
    "comment": "GR Machinery",
    "deliveryDate": "дата предоставления тех. характеристики 05.12.2025 . GLC не смог поставить",
    "daysInWork": "25 дней",
    "responsible": "#ЗНАЧ!",
    "title": "Титул 1.1 - Рахматулла Айбек"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Универсальный зажим для круглых проводников",
    "unit": "шт",
    "qty": 251,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "GLC",
    "deliveryDate": "закуп отменена",
    "daysInWork": "25 дней",
    "responsible": "#ЗНАЧ!",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Клемма заземляющая для круглых и плоских проводников",
    "unit": "шт",
    "qty": 201,
    "note": "",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "GLC",
    "deliveryDate": "закуп отменена",
    "daysInWork": "25 дней",
    "responsible": "#ЗНАЧ!",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №17",
    "date": "03.09.2025",
    "material": "Набор для термосварки 80*5 и кабеля 400мм",
    "unit": "шт",
    "qty": 63,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "",
    "daysInWork": "6.12.2025",
    "responsible": "94",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Набор для термосварки 80*5 и кабеля 120мм",
    "unit": "шт",
    "qty": 16,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "",
    "daysInWork": "6.12.2025",
    "responsible": "94",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Набор для термосварки 80*5 и кабеля 95мм",
    "unit": "шт",
    "qty": 8,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "",
    "daysInWork": "6.12.2025",
    "responsible": "94",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Набор для термосварки 80*5 и кабеля 70мм",
    "unit": "шт",
    "qty": 16,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "",
    "daysInWork": "6.12.2025",
    "responsible": "94",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Набор для термосварки 80*5 и кабеля 35мм",
    "unit": "шт",
    "qty": 347,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "",
    "daysInWork": "6.12.2025",
    "responsible": "94",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Набор для термосварки 80*5 и кабеля 16мм",
    "unit": "шт",
    "qty": 24,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "",
    "daysInWork": "6.12.2025",
    "responsible": "94",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Набор для термосварки 80*5 и кабеля 10мм",
    "unit": "шт",
    "qty": 84,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "",
    "daysInWork": "6.12.2025",
    "responsible": "94",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Уплотнительная втулка для плоских проводников",
    "unit": "шт",
    "qty": 17,
    "note": "ЦА",
    "status": "COMPLETE",
    "supplier": "6. Заявка отменена",
    "comment": "GLC",
    "deliveryDate": "21.10.25 - на согласовании спецификаций(у обьекта)",
    "daysInWork": "35 дней",
    "responsible": "",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Крестовый соединитель ДИН для плоских проводников",
    "unit": "шт",
    "qty": 121,
    "note": "ЦА",
    "status": "Нурсултан Орынтаев",
    "supplier": "4. Поставка контрагента",
    "comment": "GR Machinery",
    "deliveryDate": "обьект подал заявку 11.11.2025. GLC не смог поставить",
    "daysInWork": "14.12.2025",
    "responsible": "102",
    "title": "Титул 1.1 - Рахматулла Айбек"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Муфта стальная D25мм",
    "unit": "шт",
    "qty": 299,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "на обьекте",
    "daysInWork": "26.10.2025",
    "responsible": "53",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Направляющий профиль U-Channel",
    "unit": "шт",
    "qty": 304,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "",
    "daysInWork": "1.12.2025",
    "responsible": "89",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Трубный хомут",
    "unit": "шт",
    "qty": 304,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "",
    "daysInWork": "1.12.2025",
    "responsible": "89",
    "title": "Нурсултан Орынтаев"
  },
  {
    "id": "Заявка №18",
    "date": "03.09.2025",
    "material": "Труба ПВХ 50мм",
    "unit": "м",
    "qty": 316,
    "note": "",
    "status": "COMPLETE",
    "supplier": "5. Поставка завершена",
    "comment": "GLC",
    "deliveryDate": "на обьекте",
    "daysInWork": "23.09.2025",
    "responsible": "20",
    "title": "Нурсултан Орынтаев"
  }
]
;